import Header from './components/Header'
import './globals.css'
import Providers from './Providers'


export const metadata = {
  title: 'Big Curly Boys',
  description: 'Generated by The Boys Ltd.',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body>

        <Providers> 

        { /* Header */}
        <Header />


        { /* Navbar */}

        { /* SearchBox */}

        {children}

        </Providers>
        </body>
    </html>
  )
}
