import './globals.css'

export const metadata = {
  title: 'Big Curly Boys',
  description: 'Generated by The Boys Ltd.',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
